#name: learncha CI/CD Pipeline
#
#on:
#  push:
#    branches: [master]
#    path-ignore:
#      - '.gitignore'
#      - 'README.md'
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 1
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'corretto'
#          java-version: '11'
#          cache: 'gradle'
#      - run: ./gradlew build
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2
#
#      - name: ECR Login
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v1
#
#      - name: Set var
#        id: set-var
#        run: |
#          echo ::set-output name=ECR_REGISTRY::${{ steps.login-ecr.outputs.registry }}
#          echo ::set-output name=ECR_REPOSITORY::learncha-be-api
#          echo ::set-output name=IMAGE_TAG::${{ github.sha }}
#
#      - name: Docker image Build
#        id: build-image
#        run: |
#          echo ${{ steps.set-var.outputs.ECR_REGISTRY }}
#          docker build \
#            -f Dockerfile \
#            -t ${{ steps.set-var.outputs.ECR_REGISTRY }}/${{ steps.set-var.outputs.ECR_REPOSITORY }}:${{ steps.set-var.outputs.IMAGE_TAG }} .
#
#
#
#
#
